Feature:  prince apiConfigure create footer and api implementation show data and image slider in main component
birawat/bookstore pull request #2
Opened 2022-09-14 08:10 UTC by pkumar7777

![Screenshot (12)](https://user-images.githubusercontent.com/113450630/190096134-6a3b0486-0b63-40a0-abb0-f0e8f6d477ff.png)
![Screenshot (15)](https://user-images.githubusercontent.com/113450630/190098202-a605efdb-6e9b-4de6-a635-0f62c59e0e5b.png)
![Screenshot (13)](https://user-images.githubusercontent.com/113450630/190098278-605dcfef-916c-4434-b742-17de3321cb55.png)
![Screenshot (14)](https://user-images.githubusercontent.com/113450630/190098344-f837bef5-12a1-4ead-93e6-16f4b3adf662.png)
![Screenshot (16)](https://user-images.githubusercontent.com/113450630/190098377-c39417ba-6b53-464f-8793-fa3b266538d9.png)

2022-09-14 13:36 UTC, Vineet-panorama requested changes
Please address this comments

2022-09-14 13:36 UTC, Vineet-panorama commented on src/Home/Home.css
> +}
Formate your all file's before creating PR

2022-09-14 13:36 UTC, Vineet-panorama commented on src/index.js
Why we removed this `</React.StrictMode>`?

2022-09-14 13:54 UTC, birawat commented on src/Footer/ContactUs/Contact.css
> +    background-color:  #d8edf8, #370cc4;
Invalid css

2022-09-14 13:55 UTC, birawat commented on src/Footer/ContactUs/Contact.css
> +    background-color: #d8edf8, #370cc4
Here too

2022-09-14 13:56 UTC, birawat commented on src/Footer/ContactUs/Contact.css
> +  .form-headline:after {
Not a correct way of using pseudo element

2022-09-14 13:59 UTC, birawat commented on src/Footer/Footer.css
> +    display: 'flex';
No need of using single quote here

2022-09-14 14:08 UTC, birawat commented on src/App.js
> +import Sitemap from '../src/Footer/Sitemap';
Import directory is same for all, use the {}
Example: import {About,Blog} from '../Footer';

2022-09-14 14:09 UTC, birawat commented on src/App.css
> +  background: linear-gradient(to right, #d8edf8, #370cc4);
Why are we using background color and linear-gradient together here?

2022-09-14 14:12 UTC, birawat commented on src/Footer/ContactUs/Contact.css
> +  @media (min-width: 600px) {
In media query, also use device type. 
example: @media screen and (min-width: 600px) {
}

2022-09-14 14:13 UTC, birawat commented on src/Footer/ContactUs/Contact.css
> +  h3 {
Try to avoid to applying css directly on html elements, use class instead

2022-09-14 14:15 UTC, birawat commented on src/Footer/index.js
> +    <div className=" py-5 flex-container" class='footer'>
Why are we using classes in two different ways here?

2022-09-14 14:16 UTC, birawat commented on src/Home/index.js
> +import { useState, useEffect } from 'react'
We can also import react from the same line, so we don't have write it twice.

2022-09-14 14:24 UTC, birawat commented on src/Home/index.js
> +                            <img className="card-img-top" src={post.volumeInfo.imageLinks.thumbnail} alt="..."
Write proper text in alt

2022-09-14 14:42 UTC, pkumar7777 commented on src/App.css
> +  background: linear-gradient(to right, #d8edf8, #370cc4);
resolved

2022-09-14 14:43 UTC, pkumar7777 commented on src/Footer/ContactUs/index.js
> +                <div class="wrapper">
resolved

2022-09-14 14:46 UTC, pkumar7777 commented on src/index.js
beacuse if i add this so api runs twice.

2022-09-14 14:46 UTC, pkumar7777 commented on src/Home/Home.css
> +}
resolved

2022-09-14 14:47 UTC, pkumar7777 commented on src/Footer/ContactUs/Contact.css
> +    background-color:  #d8edf8, #370cc4;
resolved

2022-09-14 14:47 UTC, pkumar7777 commented on src/Footer/ContactUs/Contact.css
> +    background-color: #d8edf8, #370cc4
resolved

2022-09-14 14:47 UTC, pkumar7777 commented on src/Footer/ContactUs/Contact.css
> +  .form-headline:after {
resolved

2022-09-14 14:47 UTC, pkumar7777 commented on src/Footer/Footer.css
> +    display: 'flex';
resolved

2022-09-14 14:48 UTC, pkumar7777 commented on src/App.js
> +import Sitemap from '../src/Footer/Sitemap';
these are components not are functions

2022-09-14 14:50 UTC, pkumar7777 commented on src/Footer/index.js
> +    <div className=" py-5 flex-container" class='footer'>
resolved

2022-09-14 14:50 UTC, pkumar7777 commented on src/Home/index.js
> +import { useState, useEffect } from 'react'
resolved

2022-09-14 15:05 UTC, pkumar7777 commented on src/Footer/ContactUs/Contact.css
> +  h3 {
resolved

2022-09-14 15:05 UTC, pkumar7777 commented on src/Home/index.js
> +                            <img className="card-img-top" src={post.volumeInfo.imageLinks.thumbnail} alt="..."
resolved

2022-09-14 15:24 UTC, birawat requested changes
Please update the needful

2022-09-14 15:24 UTC, birawat commented on src/Footer/index.js
> +            </footer>
Use DRY approach, we are writing the data as a complete HTML, there is a huge scope of breaking this into smaller component, and rather using the entire file fetch the data from a json, build using configurable file

2022-09-14 15:24 UTC, birawat commented on src/Footer/ContactUs/Contact.css
> +body {
why are we using body css in the contact.css, please use main css or App.css files for the document level styling

2022-09-14 15:24 UTC, birawat commented on src/Home/Home.css
> +.col3 {
is it necessary to use extra clases, can we use the existing bootstrap classes

2022-09-14 15:24 UTC, birawat commented on src/Slider.js
> +
refactor this component, we can build smaller component here

2022-09-15 11:24 UTC, pkumar7777 commented on src/Slider.js
> +
resolved

2022-09-15 14:18 UTC, pkumar7777 commented on src/Home/Home.css
> +.col3 {
resolved

2022-09-15 14:21 UTC, pkumar7777 commented on src/Footer/ContactUs/Contact.css
> +body {
resolved

2022-09-15 14:23 UTC, pkumar7777 commented on src/Home/index.js
> +import { useState, useEffect } from 'react'
resolved

2022-09-15 14:24 UTC, pkumar7777 commented on src/Footer/ContactUs/Contact.css
> +body {
resolved

2022-09-15 14:24 UTC, pkumar7777 commented on src/Home/Home.css
> +.col3 {
resolved

2022-09-15 17:31 UTC, pkumar7777 commented on src/Footer/index.js
> +            </footer>
resolved

2022-09-15 17:32 UTC, pkumar7777 commented on src/Footer/ContactUs/index.js
> +                                <small></small>
resolved

2022-09-19 08:53 UTC, merged