Feature vishal/header implimentation
birawat/bookstore pull request #4
Opened 2022-09-19 09:56 UTC by vishal-panorama

Implemented Header 
![image](https://user-images.githubusercontent.com/113607898/190993266-e9c14571-e989-4711-ad65-19b29b4bb172.png)

2022-09-22 14:51 UTC, pkumar7777 requested changes

2022-09-22 14:51 UTC, pkumar7777 commented on src/App.js
>      <div >
div not needed

2022-09-22 14:51 UTC, pkumar7777 commented on src/Footer/CopyrightPolicy/index.js
>      <div>
use fragment( <></>) rather div for enclosing multiple elements

2022-09-22 14:51 UTC, pkumar7777 commented on src/Footer/index.js
>          <div>
divs not needed

2022-09-22 14:51 UTC, pkumar7777 commented on src/MainContent/Cartmodal/index.js
> +                    <CloseButton  onClick={initModal}/>
please use setModal(false) , no need to create a new function initModal

2022-09-22 14:51 UTC, pkumar7777 commented on src/MainContent/Cartmodal/index.js
> +    const initModal = () => {
remove this function as per below comment

2022-09-22 14:51 UTC, pkumar7777 commented on src/MainContent/Cartmodal/index.js
> +                    <Button variant="danger" onClick={initModal}>
same as above

2022-09-22 14:51 UTC, pkumar7777 commented on src/MainContent/ContactUs/Contact.css
> +body {
body css should be in common css, please use a single css for app level changes

2022-09-22 14:51 UTC, pkumar7777 commented on src/MainHeader/Header/CartIcon/index.js
> +  const handelCart = () => {
same as above remove this

2022-09-22 14:51 UTC, pkumar7777 commented on src/MainHeader/Header/Favorite/index.js
> +    const handelAccount =()=>{
empty function remove this

2022-09-22 17:28 UTC, merged

2022-09-23 06:06 UTC, vishal-panorama commented on src/App.js
>      <div >
Resolved

2022-09-23 06:09 UTC, vishal-panorama commented on src/Footer/index.js
>          <div>
Needed div Because returning multiple Tags (div)

2022-09-26 11:36 UTC, vishal-panorama commented on src/MainContent/Cartmodal/index.js
> +                    <CloseButton  onClick={initModal}/>
Resolved.

2022-09-26 11:37 UTC, vishal-panorama commented on src/MainContent/Cartmodal/index.js
> +                    <Button variant="danger" onClick={initModal}>
Done.

2022-09-26 11:40 UTC, vishal-panorama commented on src/MainContent/ContactUs/Contact.css
> +body {
done.

2022-09-26 11:41 UTC, vishal-panorama commented on src/MainHeader/Header/CartIcon/index.js
> +  const handelCart = () => {
done.

2022-09-26 11:43 UTC, vishal-panorama commented on src/MainHeader/Header/Favorite/index.js
> +    const handelAccount =()=>{
Done.